drop table passport;
drop table person;

CREATE TABLE Person
(
    id   int PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    name varchar(100) NOT NULL,
    age  int
);
CREATE TABLE Passport
(
    id              int PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    passport_number int NOT NULL,
    person_id       int UNIQUE REFERENCES Person (id) ON DELETE CASCADE
);